/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RepositoriesRouteImport } from './routes/repositories'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MobileAuthRouteImport } from './routes/mobile-auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareSlugRouteImport } from './routes/share.$slug'
import { Route as ReconnectGitlabRouteImport } from './routes/reconnect.gitlab'
import { Route as PapersIdRouteImport } from './routes/papers.$id'

const RepositoriesRoute = RepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileAuthRoute = MobileAuthRouteImport.update({
  id: '/mobile-auth',
  path: '/mobile-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareSlugRoute = ShareSlugRouteImport.update({
  id: '/share/$slug',
  path: '/share/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconnectGitlabRoute = ReconnectGitlabRouteImport.update({
  id: '/reconnect/gitlab',
  path: '/reconnect/gitlab',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersIdRoute = PapersIdRouteImport.update({
  id: '/papers/$id',
  path: '/papers/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mobile-auth': typeof MobileAuthRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/repositories': typeof RepositoriesRoute
  '/papers/$id': typeof PapersIdRoute
  '/reconnect/gitlab': typeof ReconnectGitlabRoute
  '/share/$slug': typeof ShareSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mobile-auth': typeof MobileAuthRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/repositories': typeof RepositoriesRoute
  '/papers/$id': typeof PapersIdRoute
  '/reconnect/gitlab': typeof ReconnectGitlabRoute
  '/share/$slug': typeof ShareSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mobile-auth': typeof MobileAuthRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/repositories': typeof RepositoriesRoute
  '/papers/$id': typeof PapersIdRoute
  '/reconnect/gitlab': typeof ReconnectGitlabRoute
  '/share/$slug': typeof ShareSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mobile-auth'
    | '/privacy'
    | '/profile'
    | '/repositories'
    | '/papers/$id'
    | '/reconnect/gitlab'
    | '/share/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mobile-auth'
    | '/privacy'
    | '/profile'
    | '/repositories'
    | '/papers/$id'
    | '/reconnect/gitlab'
    | '/share/$slug'
  id:
    | '__root__'
    | '/'
    | '/mobile-auth'
    | '/privacy'
    | '/profile'
    | '/repositories'
    | '/papers/$id'
    | '/reconnect/gitlab'
    | '/share/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MobileAuthRoute: typeof MobileAuthRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RepositoriesRoute: typeof RepositoriesRoute
  PapersIdRoute: typeof PapersIdRoute
  ReconnectGitlabRoute: typeof ReconnectGitlabRoute
  ShareSlugRoute: typeof ShareSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/repositories': {
      id: '/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-auth': {
      id: '/mobile-auth'
      path: '/mobile-auth'
      fullPath: '/mobile-auth'
      preLoaderRoute: typeof MobileAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$slug': {
      id: '/share/$slug'
      path: '/share/$slug'
      fullPath: '/share/$slug'
      preLoaderRoute: typeof ShareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconnect/gitlab': {
      id: '/reconnect/gitlab'
      path: '/reconnect/gitlab'
      fullPath: '/reconnect/gitlab'
      preLoaderRoute: typeof ReconnectGitlabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/$id': {
      id: '/papers/$id'
      path: '/papers/$id'
      fullPath: '/papers/$id'
      preLoaderRoute: typeof PapersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MobileAuthRoute: MobileAuthRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RepositoriesRoute: RepositoriesRoute,
  PapersIdRoute: PapersIdRoute,
  ReconnectGitlabRoute: ReconnectGitlabRoute,
  ShareSlugRoute: ShareSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
