/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as RepositoriesRouteImport } from "./routes/repositories"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ShareSlugRouteImport } from "./routes/share.$slug"
import { Route as PapersIdRouteImport } from "./routes/papers.$id"

const RepositoriesRoute = RepositoriesRouteImport.update({
  id: "/repositories",
  path: "/repositories",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ShareSlugRoute = ShareSlugRouteImport.update({
  id: "/share/$slug",
  path: "/share/$slug",
  getParentRoute: () => rootRouteImport,
} as any)
const PapersIdRoute = PapersIdRouteImport.update({
  id: "/papers/$id",
  path: "/papers/$id",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/repositories": typeof RepositoriesRoute
  "/papers/$id": typeof PapersIdRoute
  "/share/$slug": typeof ShareSlugRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/repositories": typeof RepositoriesRoute
  "/papers/$id": typeof PapersIdRoute
  "/share/$slug": typeof ShareSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/repositories": typeof RepositoriesRoute
  "/papers/$id": typeof PapersIdRoute
  "/share/$slug": typeof ShareSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/repositories" | "/papers/$id" | "/share/$slug"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/repositories" | "/papers/$id" | "/share/$slug"
  id: "__root__" | "/" | "/repositories" | "/papers/$id" | "/share/$slug"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RepositoriesRoute: typeof RepositoriesRoute
  PapersIdRoute: typeof PapersIdRoute
  ShareSlugRoute: typeof ShareSlugRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/repositories": {
      id: "/repositories"
      path: "/repositories"
      fullPath: "/repositories"
      preLoaderRoute: typeof RepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/share/$slug": {
      id: "/share/$slug"
      path: "/share/$slug"
      fullPath: "/share/$slug"
      preLoaderRoute: typeof ShareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/papers/$id": {
      id: "/papers/$id"
      path: "/papers/$id"
      fullPath: "/papers/$id"
      preLoaderRoute: typeof PapersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RepositoriesRoute: RepositoriesRoute,
  PapersIdRoute: PapersIdRoute,
  ShareSlugRoute: ShareSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
